pipeline {
         agent any
         stages {
                 stage('Virtual Environment') {
                 steps {
                     sh '''
                     python3 -m venv venv &&
                    . venv/bin/activate &&
                     pip install -r requirements.txt
                       '''
                   }
                   }
                   stage('Test execution') {
                 steps {
                     sh '''
                      pytest tests/ui --alluredir=allure-results
                       '''
                   }
                   }
                stage('Generate report') {
                 steps {
                     sh '''
                     allure generate allure-results -o allure-report --clean
                       '''
                    allure([
                        reportBuildPolicy: 'ALWAYS',
                        results: [[path: 'FinalProject_Trusters/allure-results']],
                        report: 'FinalProject_Trusters/allure-report'
                ])
                      
                   }
                   }
                 
               }
}
